### ISSUE TITLE
huge performance issues

### ISSUE THREAD

**Issue by sandys** [saey55/hugo-elate-theme#1]
i love your theme and the look and feel.. but it completely slows my browser down when im scrolling.

im on a dell XPS with 16 gb ram and core i7. Is there any way we can get an alternative version without all the cool animation effects ? im pretty sure that's what slowing it down

**Comment by saey55** [comment]
Hi sandys,

Glad you like the theme.
To disable the animations:

change the opacity from 0 to 100 in [`style.css`](//github.com/saey55/hugo-elate-theme/blob/master/static/css/style.css) under 
.js .to-animate,
.js .to-animate-2,
.js .single-animate {
  opacity: 100;
}

and 

delete the reference to the animate.css stylesheet in  [`head.html`](//github.com/saey55/hugo-elate-theme/blob/master/layouts/partials/head.html) 

Let me know whether this solves your performance issues.
In case this solves your performance issue, I will provide a cleaner solution to address this.

**Comment by sandys** [comment]
this is awesome - the performance is MUCH better. Although i still get occasional jerkiness.. but seriously better.

Another question - is it possible to add a separate blog section to this ? (like http://themes.gohugo.io/theme/hugo-universal-theme/blog) . We are planning on using this for my startup's home page but we need to put up company blog posts and white papers

sorry for the bother.

**Comment by instantwifi** [comment]
Switch browser, it is fast with Chrome on a old Mac Book PRO i5 with 8 GB RAM and 27 tabs open. Including HappyFox chat Toggle, Gitter, Calendar and Terminal (hugo)...
